version: "3.9"

services:
  noresm_land_sites_platform:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: "lassetk/noresm_land_sites_platform:${VERSION:-latest}"
    mem_limit: ${MEM_LIMIT:-1024M} # Max memory used
    mem_reservation: ${MEM_RESERVATION:-256M} # Minimum memory used
    cpus: ${CPUS:-1.5} # Number of CPU cores to be used
    ports:
      - "8888:8888"
      - "5006:5006"
    volumes:
      - ./data:/home/user/NorESM_LandSites_Platform/data
      - ./landsites_tools/settings.txt:/home/user/NorESM_LandSites_Platform/landsites_tools/settings.txt
      - ./landsites_tools/custom_settings:/home/user/NorESM_LandSites_Platform/landsites_tools/custom_settings
      - ./notebooks:/home/user/NorESM_LandSites_Platform/notebooks
