version: "3.9"
services:
  noresm_land_sites_platform:
    image: "lassetk/noresm_land_sites_platform:latest"
    mem_limit: 1024m # Max memory used
    mem_reservation: 256M # Minimum memory used
    cpus: 1.5 # Number of CPU cores to be used
    ports:
      - "8888:8888"
      - "5006:5006"
    volumes:
    - ./data:/home/user/NorESM_LandSites_Platform/data
    # - ./:/home/user/NorESM_LandSites_Platform/ # Map whole repository