---
name: sites_platform
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - cartopy>=0.18
  - compilers
  - gdal
  - esmpy
  - esmvalcore>=2.2.0,<2.3
  - iris>=3.0.1
  - matplotlib>3.3.1  # bug in 3.3.1 but 3.3.3 gets installed automatically
  # Non-Python dependencies
  - cdo>=1.9.7
  - eccodes!=2.19.0  # cdo dependency; something messed up with libeccodes.so
  - imagemagick
  - mpich<3.4  # avoid 3.4.1 external_2 from conda-forge like the plague
  - nco
  - scikit-learn  # may hit hw-specific issue if from pypi https://github.com/scikit-learn/scikit-learn/issues/14485

  # Multi language support:
  - ncl>=6.5.0  # this should always install 6.6.0 though

  # text editor
  - autopep8
  - flake8
  # Pip installed packages
  #- pip=19.1
  #- pip:
   #- kaggle==1.5
   #- yellowbrick==0.9
