site_name: NorESM_LandSites_Platform documentation
site_url: https://noresmhub.github.io/NorESM_LandSites_Platform/
nav:
  - Home: index.md
  - NorESM land sites: land-sites.md
  - About: about.md
  - Contributing: contributing.md
  - Code of conduct: code_of_conduct.md
extra_css:
  - stylesheets/map.css
extra_javascript:
  - javascripts/map.js
theme: readthedocs
