site_name: NorESM_LandSites_Platform documentation
site_url: https://noresmhub.github.io/NorESM_LandSites_Platform/
nav:
  - Home: index.md
  - Sites: land-sites.md
  - User guide: user_guide.md
  - About: about.md
  - Contributing & code of conduct: contributing.md
extra_css:
  - stylesheets/map.css
extra_javascript:
  - javascripts/map.js
theme: readthedocs
