site_name: NorESM Land Sites Platform technical documentation
site_url: https://noresmhub.github.io/noresm-land-sites-platform/
nav:
  - Home: index.md 
  - User guide: user_guide.md
  - Technical documentation: documentation.md
  - Sites: land-sites.md
  - About: about.md
  - Contributing & code of conduct: contributing.md
  - External tutorials and resources: resources.md
extra_css:
  - stylesheets/map.css
  - stylesheets/general.css
extra_javascript:
  - javascripts/map.js
theme: readthedocs

copyright: Copyright &copy; 2022- The NorESM Land Sites Platform Team
