name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    container: python:3.10-bullseye

    steps:
      - uses: actions/checkout@v3

      - name: Install python requirements
        run: |
          pip install -U pip
          pip install mkdocs

      - name: Build and deploy docs
        run: |
          git config --global --add safe.directory /__w/noresm-land-sites-platform/noresm-land-sites-platform
          mkdocs gh-deploy --force
